name: Publish and Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.11
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}
      
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'

      - run: echo ${{steps.version.outputs.prop}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          zip -r ${{ github.event.repository.name }}.zip . -x '*.git*'

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: '${{ github.event.repository.name }}.zip'
          tag_name: "v${{steps.version.outputs.prop}}"